//! Writes every page's snippets to `libero/tests/page_snippets.md`.

use super::*;

#[test]
fn page_snippets_are_current() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let pages = root.join("src/pages");
    let mut files = Vec::new();
    rust_files(&pages, &mut files);
    files.sort();
    let sources: Vec<(String, String)> = files
        .iter()
        .map(|file| {
            let path = file.strip_prefix(&pages).unwrap().display().to_string();
            (path, std::fs::read_to_string(file).unwrap())
        })
        .collect();

    let site = std::fs::read_to_string(root.join("src/site.rs")).unwrap();
    let samples = std::fs::read_to_string(root.join("src/samples.rs")).unwrap();

    let mut out = String::from(
        "# Page snippets\n\nGenerated by `docs/src/snippets/` from the `const` snippets and \
         the `Demo` code blocks in `docs/src/pages`, and compiled as doc-tests by \
         `libero/src/md_examples.rs`. Gitignored; do not edit: change the page, then run \
         `cargo test -p docs page_snippets`.\n",
    );
    let mut problems = Vec::new();
    let ignore = |out: &mut String, heading: &str, why: &str, body: &str| {
        let _ = write!(
            out,
            "\n## {heading}\n\nNot compiled: {why}.\n\n```rust,ignore\n{}\n```\n",
            body.trim_end()
        );
    };

    for (path, source) in &sources {
        let page = snippets(source);
        for snippet in &page {
            let heading = format!("{path} `{}`", snippet.name);
            let language = printed_language(source, &snippet.name);
            match (ignored(snippet), &language) {
                (Err(problem), _) => problems.push(format!("{path} {problem}")),
                (Ok(Some(why)), _) => ignore(&mut out, &heading, &why, &snippet.body),
                (Ok(None), Some(language)) if language != "rust" => problems.push(format!(
                    "{path} {}: printed as `{language}`, not Rust: mark it \
                     `// snippet: ignore - {language}`",
                    snippet.name
                )),
                (Ok(None), _) => match compilable(snippet, &page) {
                    Ok(code) => {
                        let _ = write!(
                            out,
                            "\n## {heading}\n\n```rust,no_run\n{PRELUDE}\n{code}```\n"
                        );
                    }
                    Err(problem) => problems.push(format!("{path} {problem}")),
                },
            }
        }
    }

    // Each page's `Demo`s, matched to its `Demo {` lines by order.
    let mut demo_count = 0;
    for Rendered { route, demos, .. } in rendered() {
        demo_count += demos.len();
        let name = format!("{route:?}");
        let name = name.trim_end_matches(" {}").trim_end_matches(" { }");
        let defined = format!("fn {name}(");
        // A definition, not a mention: a `// snippet: item .. fn Home()` comment is not a page.
        let is_page = |source: &str| {
            source.lines().any(|line| {
                let line = line.trim_start().trim_start_matches("pub ");
                line.starts_with(&defined)
            })
        };
        let Some((path, source)) = sources.iter().find(|(_, s)| is_page(s)) else {
            if !demos.is_empty() {
                problems.push(format!("{route}: no page defines `{defined}`"));
            }
            continue;
        };
        let lines = demo_markers(source);
        if demos.is_empty() && lines.is_empty() {
            continue;
        }
        if lines.len() != demos.len() {
            problems.push(format!(
                "{path}: renders {} `Demo`s but has {} `Demo {{` lines to match them to",
                demos.len(),
                lines.len()
            ));
            continue;
        }
        let page = snippets(source);
        for (code, (line, markers)) in demos.iter().zip(lines) {
            let heading = format!("{path} `Demo` at line {line}");
            let sources = demo_sources(code);
            let whole = Snippet {
                name: format!("Demo at line {line}"),
                body: String::new(),
                markers: markers.clone(),
            };
            match ignored(&whole) {
                Err(problem) => {
                    problems.push(format!("{path} {problem}"));
                    continue;
                }
                Ok(Some(why)) => {
                    ignore(&mut out, &heading, &why, &sources.join("\n\n"));
                    continue;
                }
                Ok(None) => {}
            }
            // A state that prints an ignored `const` is not compiled either,
            // for the same reason. It is listed, not dropped.
            let ignored_consts: Vec<(&Snippet, String)> = page
                .iter()
                .filter_map(|s| Some((s, ignored(s).ok()??)))
                .filter(|(s, _)| !s.body.trim().is_empty())
                .collect();
            let mut block = String::new();
            let mut skipped = String::new();
            for (state, body) in sources.into_iter().enumerate() {
                if let Some((by, why)) = ignored_consts
                    .iter()
                    .find(|(s, _)| body.contains(s.body.trim()))
                {
                    let _ = write!(
                        skipped,
                        "\nState {state} not compiled: it prints `{}`, which is not compiled: {why}.\n\n```rust,ignore\n{}\n```\n",
                        by.name,
                        body.trim_end()
                    );
                    continue;
                }
                // One `Demo` prints different code per state, so a stand-in
                // goes only into the states that name it.
                let mut kept: Vec<&String> = Vec::new();
                loop {
                    let named = |name: &str| {
                        names(&body, name) || kept.iter().any(|marker| names(marker, name))
                    };
                    let next: Vec<&String> = markers
                        .iter()
                        .filter(|marker| defines(marker).is_none_or(named))
                        .collect();
                    if next.len() == kept.len() {
                        break;
                    }
                    kept = next;
                }
                let markers = kept.into_iter().cloned().collect();
                let snippet = Snippet {
                    name: format!("Demo at line {line}, state {state}"),
                    body,
                    markers,
                };
                match compilable(&snippet, &page) {
                    // A module each, so every state has its own `Snippet`.
                    Ok(code) => {
                        let _ = write!(block, "mod state_{state} {{\nuse super::*;\n{code}}}\n");
                    }
                    Err(problem) => problems.push(format!("{path} {problem}")),
                }
            }
            let _ = write!(
                out,
                // Its own `main`, or rustdoc wraps the modules in one and
                // `super` stops reaching the prelude.
                "\n## {heading}\n\n```rust,no_run\n{PRELUDE}\n{}\n{block}\nfn main() {{}}\n```\n",
                stand_ins(&[&site, &samples, source])
            );
            out.push_str(&skipped);
        }
    }

    assert!(problems.is_empty(), "{}", problems.join("\n"));
    // Zero anywhere is the shell failing, not a page: say that, not 90 mismatches.
    assert!(
        demo_count > 0,
        "no route rendered a `Demo`: the shell likely failed"
    );
    // Gitignored, so nothing to commit. Rewritten only when it changed.
    let generated = root.join("../libero/tests/page_snippets.md");
    if std::fs::read_to_string(&generated).ok().as_deref() != Some(&out) {
        std::fs::write(&generated, &out).unwrap();
    }
}
