[package]
name = "libero-macros"
version = "0.1.0"
edition = "2024"
authors = ["Tom Dymel <tom@dymel.dev>"]
description = "Derive macros for libero."
license = "MIT OR Apache-2.0"
repository = "https://github.com/tdymel/libero"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }

[lints]
workspace = true
