mod accordion;
mod avatar;
mod badge;
mod carousel;
mod data_list;
mod icon;
mod icon_provider;
mod image;
mod image_list;
mod indicator;
mod list;
mod marquee;
mod pictogram;
mod qr_code;
mod sortable;
mod table;
mod timeline;

pub use accordion::AccordionPage;
pub use avatar::AvatarPage;
pub use badge::BadgePage;
pub use carousel::CarouselPage;
pub use data_list::DataListPage;
pub use icon::IconPage;
pub use icon_provider::IconProviderPage;
pub use image::ImagePage;
pub use image_list::ImageListPage;
pub use indicator::IndicatorPage;
pub use list::ListPage;
pub use marquee::MarqueePage;
pub use pictogram::PictogramPage;
pub use qr_code::QrCodePage;
pub use sortable::SortablePage;
pub use table::TablePage;
pub use timeline::TimelinePage;
