mod avatar;
mod badge;
mod data_list;
mod icon;
mod image;
mod indicator;
mod list;
mod qr_code;
mod table;
mod timeline;

pub use avatar::AvatarPage;
pub use badge::BadgePage;
pub use data_list::DataListPage;
pub use icon::IconPage;
pub use image::ImagePage;
pub use indicator::IndicatorPage;
pub use list::ListPage;
pub use qr_code::QrCodePage;
pub use table::TablePage;
pub use timeline::TimelinePage;
