use std::sync::LazyLock;

#[cfg(feature = "wasm-split")]
use dioxus::wasm_split;
use syntect::parsing::{ParseState, Scope, ScopeStack, SyntaxSet};

use crate::components::Input;

use super::language_catalog::{self, LANGUAGE_CATALOG};

// Generated by `build.rs` from the same catalog, filtered to just the
// languages actually enabled - plain strings, no syntect involved, so this
// stays in the main bundle even when the `wasm-split` feature also pulls
// `SYNTAX_SET` below out of it (see `highlight_split`). Powers
// `Language::is_available` without pulling the packdump back into the main
// chunk.
include!(concat!(env!("OUT_DIR"), "/enabled_languages.rs"));

/// A language recognized by [`LANGUAGE_CATALOG`] - not necessarily one this
/// build actually has a grammar for, see [`Language::is_available`].
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Language(&'static language_catalog::LanguageEntry);

impl Language {
    fn parse(value: &str) -> Option<Self> {
        let value = value.to_lowercase();
        LANGUAGE_CATALOG
            .iter()
            .find(|entry| entry.aliases.contains(&value.as_str()))
            .map(Language)
    }

    /// The token fed to [`SyntaxSet::find_syntax_by_token`] - independent of
    /// whatever alias was used to construct this `Language`.
    fn syntect_token(self) -> &'static str {
        self.0.syntect_token
    }

    pub(crate) fn label(self) -> &'static str {
        self.0.label
    }

    /// Whether this build's `code-lang-*` features actually include this
    /// language's grammar - a name can be recognized by the catalog without
    /// being compiled in.
    pub(crate) fn is_available(self) -> bool {
        ENABLED_LANGUAGE_FEATURES.contains(&self.0.feature)
    }
}

/// Unrecognized input means "don't highlight", not "guess" - resolves to
/// `Input::None` rather than defaulting to some language.
impl From<&str> for Input<Language> {
    fn from(value: &str) -> Self {
        Language::parse(value)
            .map(Input::Value)
            .unwrap_or(Input::None)
    }
}

impl From<String> for Input<Language> {
    fn from(value: String) -> Self {
        Input::from(value.as_str())
    }
}

/// Built by `build.rs` from only the languages enabled via `code-lang-*`
/// features, instead of syntect's own ~150-language default packdump.
static SYNTAX_SET: LazyLock<SyntaxSet> = LazyLock::new(|| {
    syntect::dumps::from_uncompressed_data(include_bytes!(concat!(
        env!("OUT_DIR"),
        "/syntaxes.packdump"
    )))
    .expect("build.rs writes a valid dump")
});

/// TextMate scope prefixes (checked stack-top to bottom, most specific
/// first) mapped to the token classes declared in `token_theme.rs`. Not
/// exhaustive - anything unmatched (plain punctuation, whitespace, generic
/// `meta.*`/`variable.*`) stays unstyled, which is intentional: we're
/// coloring for "good enough, consistent", not full editor fidelity.
const RAW_SCOPE_CLASSES: &[(&str, &str)] = &[
    ("punctuation.definition.string", "lsx-tok-string"),
    ("punctuation.definition.comment", "lsx-tok-comment"),
    ("comment", "lsx-tok-comment"),
    ("string", "lsx-tok-string"),
    ("constant.numeric", "lsx-tok-number"),
    ("support.constant", "lsx-tok-constant"),
    ("constant", "lsx-tok-constant"),
    ("keyword", "lsx-tok-keyword"),
    ("storage", "lsx-tok-keyword"),
    ("entity.name.function", "lsx-tok-function"),
    ("support.function", "lsx-tok-function"),
    ("support.macro", "lsx-tok-function"),
    ("entity.name.tag", "lsx-tok-tag"),
    ("entity.name.type", "lsx-tok-type"),
    ("support.type.property-name", "lsx-tok-attribute"),
    ("support.type", "lsx-tok-type"),
    ("entity.other.attribute-name", "lsx-tok-attribute"),
    ("markup.heading", "lsx-tok-heading"),
    ("markup.bold", "lsx-tok-bold"),
    ("markup.italic", "lsx-tok-italic"),
    ("markup.raw", "lsx-tok-string"),
    ("punctuation.definition", "lsx-tok-comment"),
];

static SCOPE_CLASSES: LazyLock<Vec<(Scope, &'static str)>> = LazyLock::new(|| {
    RAW_SCOPE_CLASSES
        .iter()
        .map(|(scope, class)| {
            (
                Scope::new(scope).expect("RAW_SCOPE_CLASSES entries are valid scopes"),
                *class,
            )
        })
        .collect()
});

pub(crate) type HighlightedLine = Vec<(String, Option<&'static str>)>;

/// Same shape as [`highlight`], for when there's no language to color by -
/// keeps `Code`'s rendering (line numbers included) on one code path.
pub(crate) fn plain_lines(source: &str) -> Vec<HighlightedLine> {
    source
        .lines()
        .map(|line| vec![(line.to_string(), None)])
        .collect()
}

/// `None` if the language has no bundled syntax (shouldn't happen for the
/// closed `Language` set, but `find_syntax_by_token` is fallible).
pub(crate) fn highlight(source: &str, language: Language) -> Option<Vec<HighlightedLine>> {
    let syntax = SYNTAX_SET.find_syntax_by_token(language.syntect_token())?;
    let mut parse_state = ParseState::new(syntax);
    let mut stack = ScopeStack::new();
    let mut lines = Vec::new();

    for line in syntect::util::LinesWithEndings::from(source) {
        let content_len = line.trim_end_matches(['\n', '\r']).len();
        let ops = parse_state.parse_line(line, &SYNTAX_SET).ok()?;
        let mut spans = Vec::new();
        let mut last = 0usize;

        for (pos, op) in ops {
            let pos = pos.min(content_len);
            if pos > last {
                push_span(&mut spans, &line[last..pos], &stack);
            }
            let _ = stack.apply(&op);
            last = pos;
        }
        if last < content_len {
            push_span(&mut spans, &line[last..content_len], &stack);
        }

        lines.push(spans);
    }

    Some(lines)
}

// `#[wasm_split]` drops the item's visibility on wasm32 (it rebuilds the fn
// from just `item_fn.sig`, which doesn't carry `vis`), so this stays private
// and `highlight_lazy` below re-exposes it at the visibility callers need.
#[cfg(feature = "wasm-split")]
#[wasm_split::wasm_split(code_highlighting)]
async fn highlight_split(source: String, language: Language) -> Option<Vec<HighlightedLine>> {
    highlight(&source, language)
}

/// Same as [`highlight`], but with the `wasm-split` feature on, the syntect
/// engine itself (~2MB) lives in a separate wasm chunk fetched on first call
/// instead of the main bundle - see `dioxus::wasm_split`. Without that
/// feature (or on non-wasm32 targets) this is just a plain async call with
/// nothing split out, so it works with a plain `dx serve`/`dx build`, no
/// `--wasm-split` cooperation required.
pub(crate) async fn highlight_lazy(
    source: String,
    language: Language,
) -> Option<Vec<HighlightedLine>> {
    #[cfg(feature = "wasm-split")]
    return highlight_split(source, language).await;

    #[cfg(not(feature = "wasm-split"))]
    return highlight(&source, language);
}

fn push_span(spans: &mut HighlightedLine, text: &str, stack: &ScopeStack) {
    if text.is_empty() {
        return;
    }
    spans.push((text.to_string(), classify(stack)));
}

fn classify(stack: &ScopeStack) -> Option<&'static str> {
    stack.as_slice().iter().rev().find_map(|scope| {
        SCOPE_CLASSES
            .iter()
            .find(|(prefix, _)| prefix.is_prefix_of(*scope))
            .map(|(_, class)| *class)
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn lang(name: &str) -> Language {
        Language::parse(name).unwrap_or_else(|| panic!("{name} should be in LANGUAGE_CATALOG"))
    }

    fn flat(source: &str, language: Language) -> Vec<(String, Option<&'static str>)> {
        highlight(source, language)
            .expect("language should resolve to a bundled syntax")
            .into_iter()
            .flatten()
            .collect()
    }

    #[test]
    fn language_parse_accepts_known_aliases_and_rejects_unknown() {
        assert_eq!(Language::parse("rust"), Language::parse("rs"));
        assert_eq!(Language::parse("rust"), Language::parse("RS"));
        assert_eq!(Language::parse("bash"), Language::parse("sh"));
        assert_eq!(Language::parse("md"), Language::parse("markdown"));
        assert_eq!(Language::parse("cobol"), None);
    }

    #[test]
    fn every_catalog_entry_has_a_unique_feature_name() {
        let mut features: Vec<&str> = LANGUAGE_CATALOG.iter().map(|entry| entry.feature).collect();
        let before = features.len();
        features.sort_unstable();
        features.dedup();
        assert_eq!(
            features.len(),
            before,
            "duplicate feature name in LANGUAGE_CATALOG"
        );
    }

    #[test]
    fn unrecognized_language_string_falls_back_to_no_highlighting() {
        let input: Input<Language> = "cobol".into();
        assert!(matches!(input, Input::None));
    }

    #[test]
    fn highlight_rust_classifies_keyword_string_comment_and_number() {
        let spans = flat("let x = 5; // hi\n", lang("rust"));

        assert!(
            spans
                .iter()
                .any(|(text, class)| text == "let" && *class == Some("lsx-tok-keyword"))
        );
        assert!(
            spans
                .iter()
                .any(|(text, class)| text == "5" && *class == Some("lsx-tok-number"))
        );
        assert!(
            spans
                .iter()
                .any(|(text, class)| text.contains("hi") && *class == Some("lsx-tok-comment"))
        );
    }

    #[test]
    fn highlight_rust_string_quotes_share_the_string_class() {
        let spans = flat("\"hi\"\n", lang("rust"));

        assert!(
            spans
                .iter()
                .all(|(text, class)| text.trim().is_empty() || *class == Some("lsx-tok-string"))
        );
    }

    #[test]
    fn highlight_html_classifies_tag_and_attribute() {
        let spans = flat("<div class=\"a\"></div>\n", lang("html"));

        assert!(
            spans
                .iter()
                .any(|(text, class)| text == "div" && *class == Some("lsx-tok-tag"))
        );
        assert!(
            spans
                .iter()
                .any(|(text, class)| text == "class" && *class == Some("lsx-tok-attribute"))
        );
    }

    #[test]
    fn highlight_css_classifies_property_and_color_constant() {
        let spans = flat("a { color: red; }\n", lang("css"));

        assert!(
            spans
                .iter()
                .any(|(text, class)| text == "color" && *class == Some("lsx-tok-attribute"))
        );
        assert!(
            spans
                .iter()
                .any(|(text, class)| text == "red" && *class == Some("lsx-tok-constant"))
        );
    }

    #[test]
    fn highlight_shell_classifies_keyword_and_string() {
        let spans = flat("echo \"hi\"\n", lang("bash"));

        assert!(
            spans
                .iter()
                .any(|(text, class)| text == "hi" && *class == Some("lsx-tok-string"))
        );
    }

    #[test]
    fn highlight_markdown_classifies_heading_bold_and_italic() {
        let spans = flat("# Title\n\n*a* **b**\n", lang("markdown"));

        assert!(
            spans
                .iter()
                .any(|(text, class)| text == "Title" && *class == Some("lsx-tok-heading"))
        );
        assert!(
            spans
                .iter()
                .any(|(text, class)| text == "a" && *class == Some("lsx-tok-italic"))
        );
        assert!(
            spans
                .iter()
                .any(|(text, class)| text == "b" && *class == Some("lsx-tok-bold"))
        );
    }

    #[test]
    fn highlight_never_includes_trailing_newline_in_span_text() {
        let spans = flat("let x = 1;\n", lang("rust"));
        assert!(spans.iter().all(|(text, _)| !text.contains('\n')));
    }
}
