//! One group per component, plus `CommonLabels` for the words many share.
//! Templates take named holes, filled by [`fill`](super::fill).

mod anchor;
mod avatar;
mod burger;
mod carousel;
mod cascader;
mod chips;
mod code_block;
mod color;
mod combobox;
mod common;
mod copy_button;
mod direction_toggle;
mod file_field;
mod floating_window;
mod image;
mod lightbox;
mod marquee;
mod menu;
mod nav_link;
mod notifications;
mod number_field;
mod pagination;
mod password_field;
mod phone_field;
mod pin_field;
mod repo_button;
mod scroller;
mod slider;
mod sortable;
mod spotlight;
mod stepper;
mod tags_field;
mod textarea;
mod theme_toggle;
mod tldr;

pub use anchor::AnchorLabels;
pub use avatar::AvatarLabels;
pub use burger::BurgerLabels;
pub use carousel::CarouselLabels;
pub use cascader::CascaderLabels;
pub use chips::ChipsLabels;
pub use code_block::CodeBlockLabels;
pub use color::ColorLabels;
pub use combobox::ComboboxLabels;
pub use common::CommonLabels;
pub use copy_button::CopyButtonLabels;
pub use direction_toggle::DirectionToggleLabels;
pub use file_field::FileFieldLabels;
pub use floating_window::FloatingWindowLabels;
pub use image::ImageLabels;
pub use lightbox::LightboxLabels;
pub use marquee::MarqueeLabels;
pub use menu::MenuLabels;
pub use nav_link::NavLinkLabels;
pub use notifications::NotificationsLabels;
pub use number_field::NumberFieldLabels;
pub use pagination::PaginationLabels;
pub use password_field::PasswordFieldLabels;
pub use phone_field::PhoneFieldLabels;
pub use pin_field::PinFieldLabels;
pub use repo_button::RepoButtonLabels;
pub use scroller::ScrollerLabels;
pub use slider::SliderLabels;
pub use sortable::SortableLabels;
pub use spotlight::SpotlightLabels;
pub use stepper::StepperLabels;
pub use tags_field::TagsFieldLabels;
pub use textarea::TextareaLabels;
pub use theme_toggle::ThemeToggleLabels;
pub use tldr::TldrLabels;
