// A glob over `theme`'s exports, so a new component's defaults never edit
// this import list.
use super::*;

// Deliberately not `Copy`, despite being built from `Copy` fields: at ~2KB a
// stray by-value use is a silent memcpy. Nothing needs it - `Theme::DEFAULT`
// is a `const` (so `Theme { ..Theme::DEFAULT }` still works) and `use_theme()`
// hands out `&'static Theme`.
#[derive(Clone, Debug, PartialEq)]
pub struct Theme {
    pub spacing: Sizes<u8>,
    pub radius: Sizes<u8>,
    /// Drop shadows, `xs` (resting) to `xxl` (a modal). M3's elevation levels.
    pub elevation: Sizes<&'static str>,
    pub flex: FlexDefaults,
    pub grid: GridDefaults,
    pub carousel: CarouselDefaults,
    pub center: CenterDefaults,
    pub container: ContainerDefaults,
    pub aspect_ratio: AspectRatioDefaults,
    pub collapse: CollapseDefaults,
    pub accordion: AccordionDefaults,
    pub float: FloatDefaults,
    pub floating_window: FloatingWindowDefaults,
    pub overlay: OverlayDefaults,
    pub z_index: ZIndexDefaults,
    pub popover: PopoverDefaults,
    pub progress_bar: ProgressBarDefaults,
    /// The library's one focus indicator, shared by every focusable.
    pub focus_ring: FocusRingDefaults,
    pub paper: PaperDefaults,
    pub dialog: DialogDefaults,
    pub drawer: DrawerDefaults,
    pub sidebar: SidebarDefaults,
    pub divider: DividerDefaults,
    pub splitter: SplitterDefaults,
    pub scroll_area: ScrollAreaDefaults,
    pub scroller: ScrollerDefaults,
    pub blockquote: BlockquoteDefaults,
    pub burger: BurgerDefaults,
    pub button: ButtonDefaults,
    pub chip: ChipDefaults,
    pub badge: BadgeDefaults,
    pub alert: AlertDefaults,
    pub switch: SwitchDefaults,
    pub segmented_control: SegmentedControlDefaults,
    pub checkbox: CheckboxDefaults,
    pub radio: RadioDefaults,
    /// Shared by every field: the typography of the slots stacked around a
    /// control. The frame numbers stay per component until R5.
    pub field: FieldDefaults,
    pub form: FormDefaults,
    pub fieldset: FieldsetDefaults,
    pub native_select: NativeSelectDefaults,
    pub select: SelectDefaults,
    pub multi_select: SelectDefaults,
    pub cascader: CascaderDefaults,
    pub file_field: FileFieldDefaults,
    pub pin_field: PinFieldDefaults,
    pub password_field: PasswordFieldDefaults,
    pub phone_field: PhoneFieldDefaults,
    pub tags_field: TagsFieldDefaults,
    pub text_field: TextFieldDefaults,
    pub textarea: TextareaDefaults,
    pub number_field: NumberFieldDefaults,
    /// Names, first weekday and display format for every date and time
    /// component. The one place to translate them.
    pub date: DateDefaults,
    pub date_picker: DatePickerDefaults,
    pub date_field: DateFieldDefaults,
    pub time_picker: TimePickerDefaults,
    pub combobox: ComboboxDefaults,
    pub autocomplete: AutocompleteDefaults,
    pub color_picker: ColorPickerDefaults,
    pub color_field: ColorFieldDefaults,
    pub color_swatch: ColorSwatchDefaults,
    pub slider: SliderDefaults,
    pub list: ListDefaults,
    pub loader: LoaderDefaults,
    pub indicator: IndicatorDefaults,
    pub skeleton: SkeletonDefaults,
    pub spotlight: SpotlightDefaults,
    pub marquee: MarqueeDefaults,
    pub notifications: NotificationsDefaults,
    pub data_list: DataListDefaults,
    pub table: TableDefaults,
    pub timeline: TimelineDefaults,
    pub tabs: TabsDefaults,
    pub stepper: StepperDefaults,
    pub tree: TreeDefaults,
    pub title: TitleDefaults,
    pub text: TextDefaults,
    pub tooltip: TooltipDefaults,
    pub hover_card: HoverCardDefaults,
    pub code: CodeDefaults,
    pub code_block: CodeBlockDefaults,
    pub header: HeaderDefaults,
    pub icon: IconDefaults,
    pub action_icon: ActionIconDefaults,
    pub qr_code: QrCodeDefaults,
    pub image: ImageDefaults,
    pub image_list: ImageListDefaults,
    pub lightbox: LightboxDefaults,
    pub avatar: AvatarDefaults,
    pub avatar_group: AvatarGroupDefaults,
    pub mark: MarkDefaults,
    pub kbd: KbdDefaults,
    pub menu: MenuDefaults,
    pub menubar: MenubarDefaults,
    pub pagination: PaginationDefaults,
    /// Every string `Pagination` shows a reader. Swapped whole for a locale.
    pub pagination_labels: PaginationLabels,
    pub nav_link: NavLinkDefaults,
    pub anchor: AnchorDefaults,
    pub primary: HexColor,
    pub secondary: HexColor,
    pub error: HexColor,
    pub warning: HexColor,
    pub info: HexColor,
    pub success: HexColor,
    /// Text-dark neutral: the label and outline color of a `neutral` control.
    pub neutral: HexColor,
    pub muted: HexColor,
    /// What text is set in, and the page it is set on. Every colour role is
    /// derived against `surface`, so a dark theme is a theme whose `surface`
    /// is dark - not one that redefines "white". `Paper`'s own background is
    /// a different thing: the card drawn on top of this one.
    pub ink: HexColor,
    pub surface: HexColor,
    pub font_smoothing: bool,
}

impl Theme {
    pub const DEFAULT: Theme = Theme {
        spacing: Sizes::new(4, 8, 12, 16, 20, 24),
        radius: Sizes::new(2, 4, 8, 16, 32, 64),
        elevation: Sizes::new(
            "0 1px 2px rgba(0, 0, 0, 0.10), 0 1px 3px rgba(0, 0, 0, 0.06)",
            "0 1px 2px rgba(0, 0, 0, 0.10), 0 2px 6px rgba(0, 0, 0, 0.10)",
            "0 2px 4px rgba(0, 0, 0, 0.10), 0 4px 10px rgba(0, 0, 0, 0.12)",
            "0 4px 8px rgba(0, 0, 0, 0.10), 0 8px 20px rgba(0, 0, 0, 0.14)",
            "0 8px 16px rgba(0, 0, 0, 0.12), 0 12px 32px rgba(0, 0, 0, 0.18)",
            "0 12px 24px rgba(0, 0, 0, 0.14), 0 20px 48px rgba(0, 0, 0, 0.22)",
        ),
        flex: FlexDefaults::DEFAULT,
        grid: GridDefaults::DEFAULT,
        carousel: CarouselDefaults::DEFAULT,
        center: CenterDefaults::DEFAULT,
        container: ContainerDefaults::DEFAULT,
        aspect_ratio: AspectRatioDefaults::DEFAULT,
        collapse: CollapseDefaults::DEFAULT,
        accordion: AccordionDefaults::DEFAULT,
        float: FloatDefaults::DEFAULT,
        floating_window: FloatingWindowDefaults::DEFAULT,
        overlay: OverlayDefaults::DEFAULT,
        z_index: ZIndexDefaults::DEFAULT,
        popover: PopoverDefaults::DEFAULT,
        focus_ring: FocusRingDefaults::DEFAULT,
        paper: PaperDefaults::DEFAULT,
        dialog: DialogDefaults::DEFAULT,
        drawer: DrawerDefaults::DEFAULT,
        sidebar: SidebarDefaults::DEFAULT,
        divider: DividerDefaults::DEFAULT,
        splitter: SplitterDefaults::DEFAULT,
        scroll_area: ScrollAreaDefaults::DEFAULT,
        scroller: ScrollerDefaults::DEFAULT,
        blockquote: BlockquoteDefaults::DEFAULT,
        burger: BurgerDefaults::DEFAULT,
        button: ButtonDefaults::DEFAULT,
        chip: ChipDefaults::DEFAULT,
        alert: AlertDefaults::DEFAULT,
        badge: BadgeDefaults::DEFAULT,
        progress_bar: ProgressBarDefaults::DEFAULT,
        switch: SwitchDefaults::DEFAULT,
        segmented_control: SegmentedControlDefaults::DEFAULT,
        checkbox: CheckboxDefaults::DEFAULT,
        radio: RadioDefaults::DEFAULT,
        field: FieldDefaults::DEFAULT,
        native_select: NativeSelectDefaults::DEFAULT,
        select: SelectDefaults::DEFAULT,
        multi_select: SelectDefaults::DEFAULT,
        file_field: FileFieldDefaults::DEFAULT,
        form: FormDefaults::DEFAULT,
        fieldset: FieldsetDefaults::DEFAULT,
        pin_field: PinFieldDefaults::DEFAULT,
        password_field: PasswordFieldDefaults::DEFAULT,
        phone_field: PhoneFieldDefaults::DEFAULT,
        tags_field: TagsFieldDefaults::DEFAULT,
        cascader: CascaderDefaults::DEFAULT,
        text_field: TextFieldDefaults::DEFAULT,
        textarea: TextareaDefaults::DEFAULT,
        number_field: NumberFieldDefaults::DEFAULT,
        date: DateDefaults::ENGLISH,
        date_picker: DatePickerDefaults::DEFAULT,
        date_field: DateFieldDefaults::DEFAULT,
        time_picker: TimePickerDefaults::DEFAULT,
        autocomplete: AutocompleteDefaults::DEFAULT,
        color_picker: ColorPickerDefaults::DEFAULT,
        color_field: ColorFieldDefaults::DEFAULT,
        color_swatch: ColorSwatchDefaults::DEFAULT,
        combobox: ComboboxDefaults::DEFAULT,
        slider: SliderDefaults::DEFAULT,
        list: ListDefaults::DEFAULT,
        loader: LoaderDefaults::DEFAULT,
        indicator: IndicatorDefaults::DEFAULT,
        skeleton: SkeletonDefaults::DEFAULT,
        spotlight: SpotlightDefaults::DEFAULT,
        marquee: MarqueeDefaults::DEFAULT,
        notifications: NotificationsDefaults::DEFAULT,
        table: TableDefaults::DEFAULT,
        timeline: TimelineDefaults::DEFAULT,
        tabs: TabsDefaults::DEFAULT,
        stepper: StepperDefaults::DEFAULT,
        data_list: DataListDefaults::DEFAULT,
        tree: TreeDefaults::DEFAULT,
        title: TitleDefaults::DEFAULT,
        text: TextDefaults::DEFAULT,
        tooltip: TooltipDefaults::DEFAULT,
        hover_card: HoverCardDefaults::DEFAULT,
        code: CodeDefaults::DEFAULT,
        code_block: CodeBlockDefaults::DEFAULT,
        header: HeaderDefaults::DEFAULT,
        icon: IconDefaults::DEFAULT,
        action_icon: ActionIconDefaults::DEFAULT,
        qr_code: QrCodeDefaults::DEFAULT,
        image: ImageDefaults::DEFAULT,
        image_list: ImageListDefaults::DEFAULT,
        lightbox: LightboxDefaults::DEFAULT,
        avatar: AvatarDefaults::DEFAULT,
        avatar_group: AvatarGroupDefaults::DEFAULT,
        mark: MarkDefaults::DEFAULT,
        kbd: KbdDefaults::DEFAULT,
        menu: MenuDefaults::DEFAULT,
        menubar: MenubarDefaults::DEFAULT,
        pagination: PaginationDefaults::DEFAULT,
        pagination_labels: PaginationLabels::ENGLISH,
        nav_link: NavLinkDefaults::DEFAULT,
        anchor: AnchorDefaults::DEFAULT,
        primary: HexColor::new(0x228BE6),
        secondary: HexColor::new(0x7950F2),
        error: HexColor::new(0xFA5252),
        warning: HexColor::new(0xFAB005),
        info: HexColor::new(0x15AABF),
        success: HexColor::new(0x40C057),
        neutral: HexColor::new(0x373A3C),
        muted: HexColor::new(0x868E96),
        ink: HexColor::new(0x000000),
        surface: HexColor::new(0xFFFFFF),
        font_smoothing: true,
    };

    /// The library's dark counterpart to [`DEFAULT`](Self::DEFAULT), and the
    /// dark half of [`ThemeSet::DEFAULT`](crate::theme::ThemeSet::DEFAULT):
    /// an app gets a working dark scheme without authoring a theme.
    ///
    /// Almost all of it is the default theme. The palette bases do not move -
    /// `primary` is the brand blue on both pages, and the text and fill roles
    /// are derived against `surface`, so each one walks its own ramp the
    /// right way here (see `theme::stylesheet::push_color_declarations`). The
    /// `muted` ramp does not move either: it is mixed between `ink` and
    /// `surface`, so swapping those two is what turns it round.
    ///
    /// What is spelled out is everything that is *not* derived: the two ends
    /// of the page, the `neutral` control colour - which is a text-dark
    /// neutral on paper and so has to be a text-light one here - and the five
    /// `*Defaults` that carry literal CSS colours rather than theme ones.
    pub const DARK: Theme = Theme {
        // Mantine's `dark.7`, with `dark.6` as the card in `PaperDefaults`.
        surface: HexColor::new(0x1A1B1E),
        ink: HexColor::new(0xE9ECEF),
        // The counterpart of the default's `#373A3C`: what a `neutral`
        // control is labelled and outlined in when it must not compete with
        // the page's accent.
        neutral: HexColor::new(0xCED4DA),
        paper: PaperDefaults::DARK,
        code: CodeDefaults::DARK,
        code_block: CodeBlockDefaults::DARK,
        kbd: KbdDefaults::DARK,
        tooltip: TooltipDefaults::DARK,
        ..Theme::DEFAULT
    };
}
