mod autocomplete;
mod checkbox;
mod color_field;
mod color_picker;
mod fieldset;
mod file_field;
mod form;
mod getting_started;
mod multi_select;
mod native_select;
mod number_field;
mod password_field;
mod pin_field;
mod radio_group;
mod range_slider;
mod select;
mod slider;
mod switch;
mod text_field;
mod textarea;

pub use autocomplete::AutocompletePage;
pub use checkbox::CheckboxPage;
pub use color_field::ColorFieldPage;
pub use color_picker::ColorPickerPage;
pub use fieldset::FieldsetPage;
pub use file_field::FileFieldPage;
pub use form::FormPage;
pub use getting_started::FormGettingStartedPage;
pub use multi_select::MultiSelectPage;
pub use native_select::NativeSelectPage;
pub use number_field::NumberFieldPage;
pub use password_field::PasswordFieldPage;
pub use pin_field::PinFieldPage;
pub use radio_group::RadioGroupPage;
pub use range_slider::RangeSliderPage;
pub use select::SelectPage;
pub use slider::SliderPage;
pub use switch::SwitchPage;
pub use text_field::TextFieldPage;
pub use textarea::TextareaPage;
