// Pages sharing a label ("Getting started", "Overview") get theirs by section.
pub(super) fn aliases(group: Option<&str>, label: &str) -> &'static [&'static str] {
    match (group, label) {
        (Some("About"), "Getting started") => &[
            "install",
            "installation",
            "setup",
            "quick start",
            "introduction",
            "cargo add",
        ],
        (Some("Form"), "Getting started") => &["forms", "use_field", "validation", "form state"],
        (Some("Accessibility"), "Overview") => &[
            "a11y",
            "aria",
            "screen reader",
            "keyboard navigation",
            "wcag",
        ],
        (Some("Hooks"), "Overview") => &["hooks", "use_", "utilities"],
        _ => label_aliases(label),
    }
}

// Hidden search names other libraries use for a page, and related words, by its label.
fn label_aliases(label: &str) -> &'static [&'static str] {
    match label {
        "Philosophy" => &["principles", "design goals", "vision"],
        "Styling" => &["css", "sx", "style props", "class", "custom styles"],
        "Theming" => &[
            "theme",
            "colors",
            "colours",
            "palette",
            "design tokens",
            "css variables",
            "dark mode",
        ],
        "Localization" => &[
            "i18n",
            "l10n",
            "translation",
            "language",
            "locale",
            "internationalization",
        ],
        "Providers" => &["context", "provider", "setup", "icon provider"],
        "Platform" => &["web", "desktop", "mobile", "native", "blitz", "wasm"],
        "Credits" => &["license", "attribution", "acknowledgements", "thanks"],
        "Box" => &["div", "element", "polymorphic"],
        "Paper" => &["card", "surface", "panel", "shadow", "elevation"],
        "Flex" => &[
            "stack", "row", "column", "group", "flexbox", "hstack", "vstack",
        ],
        "Grid" => &["simple grid", "layout", "css grid", "columns"],
        "Center" => &["centre", "align", "middle"],
        "Container" => &["max width", "wrapper", "content width"],
        "AspectRatio" => &["aspect ratio", "ratio"],
        "Divider" => &["separator", "rule", "hr"],
        "Collapse" => &["expand", "disclosure", "details", "show hide"],
        "Float" => &["floating"],
        "Header" => &["app bar", "top bar", "navbar"],
        "Sidebar" => &["navbar", "aside", "app shell", "side nav", "sidenav"],
        "Splitter" => &["resizable", "split pane", "panel group"],
        "Transition" => &["animate", "fade", "slide", "enter", "exit", "motion"],
        "ScrollArea" => &["scrollbar", "overflow", "scroll", "custom scrollbar"],
        "Scroller" => &["horizontal scroll", "scroll buttons", "overflow", "strip"],
        "Button" => &["btn", "click", "submit"],
        "ActionIcon" => &["icon button", "iconbutton"],
        "ButtonGroup" => &["button group", "attached buttons", "split button"],
        "Copy" => &["clipboard", "copy"],
        "DirectionToggle" => &["rtl", "ltr", "direction"],
        "Repository" => &["github", "repository"],
        "ThemeSwitcher" => &["dark mode", "color scheme", "light dark"],
        "Tldr" => &["summarize", "summary", "ai", "chatgpt", "claude"],
        "Toolbar" => &["tool bar", "action bar", "button bar"],
        "Form" => &["form field", "validation", "submit"],
        "Fieldset" => &["group", "legend"],
        "TextField" => &["input", "text input", "textinput", "text box", "textbox"],
        "Textarea" => &["multiline", "text area"],
        "RichTextEditor" => &[
            "wysiwyg",
            "rich text",
            "text editor",
            "markdown editor",
            "contenteditable",
        ],
        "PasswordField" => &["password input", "secret"],
        "PhoneField" => &["phone input", "tel", "telephone"],
        "NumberField" => &["number input", "numeric", "spinner", "stepper"],
        "PinField" => &["pin input", "otp", "verification code"],
        "Autocomplete" => &["typeahead", "suggest", "search select"],
        "Select" => &["dropdown", "drop down", "listbox"],
        "MultiSelect" => &["multi select", "multiple select", "dropdown"],
        "TagsField" => &["tags input", "taginput", "chips input"],
        "Cascader" => &["cascading select", "nested select"],
        "NativeSelect" => &["native dropdown", "html select"],
        "Combobox" => &["combo box", "dropdown", "autocomplete"],
        "Checkbox" => &["check box", "tick"],
        "Chip" => &["tag", "pill", "toggle chip"],
        "Switch" => &["toggle", "toggle switch", "on off"],
        "RadioGroup" => &["radio", "radio button", "option group"],
        "SegmentedControl" => &["segmented button", "button group", "toggle group"],
        "Slider" => &["range", "track"],
        "RangeSlider" => &["range", "two thumb", "min max"],
        "Rating" => &["stars", "star rating", "review score"],
        "ColorField" => &["color input", "colour"],
        "ColorPicker" => &["colour picker", "eyedropper", "swatch"],
        "ChronoField" => &[
            "DateField",
            "date picker",
            "datepicker",
            "date input",
            "time field",
            "time input",
            "datetime",
        ],
        "ChronoPicker" => &[
            "calendar",
            "date picker",
            "datepicker",
            "time picker",
            "datetime",
        ],
        "FileField" => &["file input", "upload", "dropzone", "file picker"],
        "ImageCropper" => &["crop", "cropper", "image crop", "avatar editor"],
        "Anchor" => &["link", "toc", "table of contents"],
        "NavLink" => &["nav item", "menu item", "link"],
        "BottomNavigation" => &["tab bar", "navigation bar", "mobile nav"],
        "Burger" => &["hamburger", "menu button", "nav toggle"],
        "Tabs" => &["tab list", "tabbed"],
        "Menubar" => &["menu bar"],
        "Pagination" => &["pager", "paging", "page numbers"],
        "Stepper" => &["steps", "wizard", "progress steps"],
        "Tree" => &["treeview", "tree view", "hierarchy", "file tree"],
        "Overlay" => &["backdrop", "scrim"],
        "Modal" => &["dialog", "popup"],
        "Dialog" => &["modal", "alert dialog", "confirm"],
        "Drawer" => &["sheet", "side panel", "offcanvas"],
        "Popover" => &["popup", "popper", "dropdown"],
        "Tooltip" => &["hint", "hover text", "title"],
        "HoverCard" => &["hover card", "preview card"],
        "Menu" => &["dropdown menu", "context menu", "actions menu"],
        "Spotlight" => &["command palette", "command k", "cmdk", "search"],
        "ShortcutHelp" => &["keyboard shortcuts", "hotkeys", "cheat sheet"],
        "Lightbox" => &["image viewer", "gallery", "zoom"],
        "FloatingWindow" => &["window", "draggable", "floating panel"],
        "Tour" => &[
            "onboarding",
            "walkthrough",
            "coachmark",
            "product tour",
            "guide",
        ],
        "Alert" => &["banner", "callout", "message", "notice", "warning"],
        "Notifications" => &["toast", "snackbar", "notify", "notification"],
        "Loader" => &["spinner", "loading", "activity indicator"],
        "ProgressBar" => &["progress", "meter"],
        "Skeleton" => &["placeholder", "shimmer", "loading"],
        // "icons" on all three, so "Icon" and "Icons" list the providers too (1445).
        "Icon" => &["icons", "glyph", "icon box"],
        "Pictogram" => &["icons", "svg", "lucide", "inline svg", "glyph"],
        "IconProvider" => &[
            "icons",
            "icon provider",
            "icon set",
            "icon theme",
            "swap icons",
            "lucide",
            "material",
            "tabler",
            "bootstrap",
            "phosphor",
        ],
        "Badge" => &["label", "tag", "pill", "chip"],
        "Indicator" => &["dot", "status dot", "notification badge"],
        "Avatar" => &["profile picture", "user picture", "initials"],
        "Image" => &["img", "picture", "photo"],
        "ImageList" => &["gallery", "masonry", "image grid"],
        "Audio" => &["sound", "music", "audio player", "podcast"],
        "Video" => &["video player", "movie", "media player", "clip"],
        "Carousel" => &["slideshow", "slider", "swiper"],
        "List" => &["ul", "ol", "bullet list"],
        "DataList" => &["description list", "definition list", "key value"],
        "Sortable" => &["drag and drop", "dnd", "reorder", "sortable list"],
        "Kanban" => &["board", "task board", "trello", "drag and drop", "columns"],
        "Table" => &["data grid", "datagrid", "datatable", "spreadsheet", "rows"],
        "Timeline" => &["history", "activity feed"],
        "Accordion" => &["expansion panel", "collapsible", "disclosure"],
        "Marquee" => &["ticker", "scrolling text"],
        "QrCode" => &["qr", "qrcode", "barcode"],
        "Title" => &["heading", "h1", "headline"],
        "Text" => &["typography", "paragraph", "body text", "font"],
        "Mark" => &["highlight"],
        "Code" => &["inline code", "monospace"],
        "Kbd" => &["keyboard", "key", "shortcut"],
        "CodeBlock" => &["pre", "code snippet", "syntax highlight"],
        "Blockquote" => &["quote", "citation"],
        "FocusTrap" => &["focus lock", "focus scope"],
        "VisuallyHidden" => &["sr only", "screen reader only", "hidden"],
        "Unique ID" => &["use_id", "id"],
        "Element handle" => &["use_element", "ref", "measure"],
        "Focus return" => &["use_focus_return", "restore focus"],
        "Drag" => &["use_drag", "pointer"],
        "Intersection" => &["use_intersection", "use_in_viewport", "viewport", "visible"],
        "Long press" => &["use_long_press", "hold"],
        "Swipe" => &["use_swipe", "use_edge_swipe", "gesture", "edge swipe"],
        "Media" => &["use_media", "audio", "video", "player"],
        "Fullscreen" => &["use_fullscreen", "full screen", "maximize"],
        "Back button" => &["use_back", "android", "hardware back"],
        "Save file" => &["save_file", "download", "export", "share"],
        "Geolocation" => &[
            "use_geolocation",
            "location",
            "gps",
            "position",
            "permission",
        ],
        "Local storage" => &[
            "use_local_storage",
            "use_session_storage",
            "session storage",
            "persist",
            "remember",
        ],
        "IndexedDB" => &[
            "use_indexed_db",
            "indexeddb",
            "idb",
            "persist",
            "offline",
            "database",
        ],
        "User media" => &[
            "use_user_media",
            "use_user_media_devices",
            "camera",
            "microphone",
            "webcam",
            "record",
            "photo",
        ],
        "System notifications" => &[
            "use_system_notification",
            "use_push_subscription",
            "push",
            "web push",
            "desktop notification",
            "service worker",
        ],
        "Timers" => &["use_timeout", "use_interval", "setTimeout", "setInterval"],
        "Debounce and throttle" => &[
            "use_debounced_value",
            "use_debounced_callback",
            "use_throttled_value",
            "use_throttled_callback",
        ],
        "History" => &["use_history", "undo", "redo"],
        "Hotkeys" => &["use_hotkeys", "keyboard shortcut", "keybinding"],
        "Media query" => &["use_media_query", "use_is_mobile", "breakpoint", "mobile"],
        "Theme set" => &["use_theme_set", "switch theme"],
        "Stylesheet" => &["use_stylesheet", "css"],
        "Accessibility settings" => &["use_accessibility", "reduced motion", "contrast"],
        _ => &[],
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::nav::tree::pages;

    #[test]
    fn every_page_has_search_words() {
        for (path, label, group) in pages() {
            assert!(!aliases(group, label).is_empty(), "{path}");
        }
    }
}
