use crate::theme::Size;

#[repr(u16)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Property {
    Background,
    Width,
    Height,
    Padding,
    PaddingTop,
    PaddingLeft,
    PaddingRight,
    PaddingBottom,
    MarginLeft,
    MarginRight,
    MarginTop,
    MarginBottom,
    Margin,
    Display,
    FlexDirection,
    FlexWrap,
    AlignItems,
    JustifyContent,
    Gap,
    GridTemplateColumns,
    GridColumn,
    MaxWidth,
    MaxHeight,
    FontFamily,
    FontSize,
    FontWeight,
    LetterSpacing,
    LineHeight,
    TextDecoration,
    Border,
    BorderTop,
    BorderRight,
    BorderBottom,
    BorderLeft,
    Color,
    Flex,
    FlexGrow,
    Content,
    BorderWidth,
    BorderStyle,
    BorderColor,
    BorderRightColor,
    BorderBottomColor,
    FlexShrink,
    AlignSelf,
    WhiteSpace,
    UserSelect,
    Position,
    Top,
    Right,
    Overflow,
    Clip,
    ObjectFit,
    BorderRadius,
    Cursor,
    Opacity,
    PointerEvents,
    ListStyle,
    MinWidth,
    MinHeight,
    AspectRatio,
    Outline,
    OutlineOffset,
    Inset,
    ZIndex,
    Transition,
    BackdropFilter,
    BoxShadow,
    TextAlign,
    ScrollMargin,
    Transform,
    Visibility,
}

impl Property {
    pub fn parse(property: &str) -> Option<Self> {
        match property {
            "background" => Some(Self::Background),
            "width" => Some(Self::Width),
            "height" => Some(Self::Height),
            "padding" => Some(Self::Padding),
            "padding-top" => Some(Self::PaddingTop),
            "padding-left" => Some(Self::PaddingLeft),
            "padding-right" => Some(Self::PaddingRight),
            "padding-bottom" => Some(Self::PaddingBottom),
            "margin-left" => Some(Self::MarginLeft),
            "margin-right" => Some(Self::MarginRight),
            "margin-top" => Some(Self::MarginTop),
            "margin-bottom" => Some(Self::MarginBottom),
            "margin" => Some(Self::Margin),
            "display" => Some(Self::Display),
            "flex-direction" => Some(Self::FlexDirection),
            "flex-wrap" => Some(Self::FlexWrap),
            "align-items" => Some(Self::AlignItems),
            "justify-content" => Some(Self::JustifyContent),
            "gap" => Some(Self::Gap),
            "grid-template-columns" => Some(Self::GridTemplateColumns),
            "grid-column" => Some(Self::GridColumn),
            "max-width" => Some(Self::MaxWidth),
            "max-height" => Some(Self::MaxHeight),
            "font-family" => Some(Self::FontFamily),
            "font-size" => Some(Self::FontSize),
            "font-weight" => Some(Self::FontWeight),
            "letter-spacing" => Some(Self::LetterSpacing),
            "line-height" => Some(Self::LineHeight),
            "text-decoration" => Some(Self::TextDecoration),
            "border" => Some(Self::Border),
            "border-top" => Some(Self::BorderTop),
            "border-right" => Some(Self::BorderRight),
            "border-bottom" => Some(Self::BorderBottom),
            "border-left" => Some(Self::BorderLeft),
            "color" => Some(Self::Color),
            "flex" => Some(Self::Flex),
            "flex-grow" => Some(Self::FlexGrow),
            "content" => Some(Self::Content),
            "border-width" => Some(Self::BorderWidth),
            "border-style" => Some(Self::BorderStyle),
            "border-color" => Some(Self::BorderColor),
            "border-right-color" => Some(Self::BorderRightColor),
            "border-bottom-color" => Some(Self::BorderBottomColor),
            "flex-shrink" => Some(Self::FlexShrink),
            "align-self" => Some(Self::AlignSelf),
            "white-space" => Some(Self::WhiteSpace),
            "user-select" => Some(Self::UserSelect),
            "position" => Some(Self::Position),
            "top" => Some(Self::Top),
            "right" => Some(Self::Right),
            "overflow" => Some(Self::Overflow),
            "clip" => Some(Self::Clip),
            "object-fit" => Some(Self::ObjectFit),
            "border-radius" => Some(Self::BorderRadius),
            "cursor" => Some(Self::Cursor),
            "opacity" => Some(Self::Opacity),
            "pointer-events" => Some(Self::PointerEvents),
            "list-style" => Some(Self::ListStyle),
            "min-width" => Some(Self::MinWidth),
            "min-height" => Some(Self::MinHeight),
            "aspect-ratio" => Some(Self::AspectRatio),
            "outline" => Some(Self::Outline),
            "outline-offset" => Some(Self::OutlineOffset),
            "inset" => Some(Self::Inset),
            "z-index" => Some(Self::ZIndex),
            "transition" => Some(Self::Transition),
            "backdrop-filter" => Some(Self::BackdropFilter),
            "box-shadow" => Some(Self::BoxShadow),
            "text-align" => Some(Self::TextAlign),
            "scroll-margin" => Some(Self::ScrollMargin),
            "transform" => Some(Self::Transform),
            "visibility" => Some(Self::Visibility),
            _ => None,
        }
    }

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Background => "background",
            Self::Width => "width",
            Self::Height => "height",
            Self::Padding => "padding",
            Self::PaddingTop => "padding-top",
            Self::PaddingLeft => "padding-left",
            Self::PaddingRight => "padding-right",
            Self::PaddingBottom => "padding-bottom",
            Self::MarginLeft => "margin-left",
            Self::MarginRight => "margin-right",
            Self::MarginTop => "margin-top",
            Self::MarginBottom => "margin-bottom",
            Self::Margin => "margin",
            Self::Display => "display",
            Self::FlexDirection => "flex-direction",
            Self::FlexWrap => "flex-wrap",
            Self::AlignItems => "align-items",
            Self::JustifyContent => "justify-content",
            Self::Gap => "gap",
            Self::GridTemplateColumns => "grid-template-columns",
            Self::GridColumn => "grid-column",
            Self::MaxWidth => "max-width",
            Self::MaxHeight => "max-height",
            Self::FontFamily => "font-family",
            Self::FontSize => "font-size",
            Self::FontWeight => "font-weight",
            Self::LetterSpacing => "letter-spacing",
            Self::LineHeight => "line-height",
            Self::TextDecoration => "text-decoration",
            Self::Border => "border",
            Self::BorderTop => "border-top",
            Self::BorderRight => "border-right",
            Self::BorderBottom => "border-bottom",
            Self::BorderLeft => "border-left",
            Self::Color => "color",
            Self::Flex => "flex",
            Self::FlexGrow => "flex-grow",
            Self::Content => "content",
            Self::BorderWidth => "border-width",
            Self::BorderStyle => "border-style",
            Self::BorderColor => "border-color",
            Self::BorderRightColor => "border-right-color",
            Self::BorderBottomColor => "border-bottom-color",
            Self::FlexShrink => "flex-shrink",
            Self::AlignSelf => "align-self",
            Self::WhiteSpace => "white-space",
            Self::UserSelect => "user-select",
            Self::Position => "position",
            Self::Top => "top",
            Self::Right => "right",
            Self::Overflow => "overflow",
            Self::Clip => "clip",
            Self::ObjectFit => "object-fit",
            Self::BorderRadius => "border-radius",
            Self::Cursor => "cursor",
            Self::Opacity => "opacity",
            Self::PointerEvents => "pointer-events",
            Self::ListStyle => "list-style",
            Self::MinWidth => "min-width",
            Self::MinHeight => "min-height",
            Self::AspectRatio => "aspect-ratio",
            Self::Outline => "outline",
            Self::OutlineOffset => "outline-offset",
            Self::Inset => "inset",
            Self::ZIndex => "z-index",
            Self::Transition => "transition",
            Self::BackdropFilter => "backdrop-filter",
            Self::BoxShadow => "box-shadow",
            Self::TextAlign => "text-align",
            Self::ScrollMargin => "scroll-margin",
            Self::Transform => "transform",
            Self::Visibility => "visibility",
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum SxPropertyKey {
    Known(Property),
    Raw(String),
}

impl SxPropertyKey {
    pub fn parse(property: impl Into<String>) -> Self {
        let property = property.into();
        match Property::parse(&property) {
            Some(property) => Self::Known(property),
            None => Self::Raw(property),
        }
    }

    pub fn as_str(&self) -> &str {
        match self {
            Self::Known(property) => property.as_str(),
            Self::Raw(property) => property.as_str(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum SxModifierKey {
    Selector(String),
    Condition(String),
    Breakpoint(Size),
}
