//! Compiles every ` ```rust ` block in `docs/public/md/*.md` as a doc-test, so a
//! printed example that stops compiling fails `cargo test -p libero`. Only built
//! under `cfg(doctest)`; run just these with `cargo test -p libero --doc md_examples`.
//!
//! A block that is a fragment on purpose (it continues an earlier block, or
//! names a placeholder like `Route`) is fenced `rust,ignore`. A bare ` ``` `
//! fence is Rust to rustdoc too, so plain text is fenced `text`.
//! `tests/all/md_examples.rs` checks that every md file is listed here.

macro_rules! md_pages {
    ($($page:ident => $file:literal,)*) => {
        $(
            #[doc = include_str!(concat!("../../docs/public/md/", $file, ".md"))]
            pub struct $page;
        )*
    };
}

md_pages! {
    Accordion => "accordion",
    ActionIcon => "action_icon",
    Alert => "alert",
    Anchor => "anchor",
    AspectRatio => "aspect_ratio",
    Autocomplete => "autocomplete",
    Avatar => "avatar",
    Badge => "badge",
    Blockquote => "blockquote",
    Box => "box",
    Burger => "burger",
    Button => "button",
    Carousel => "carousel",
    Cascader => "cascader",
    Center => "center",
    Checkbox => "checkbox",
    Chip => "chip",
    Code => "code",
    CodeBlock => "code_block",
    Collapse => "collapse",
    ColorField => "color_field",
    ColorPicker => "color_picker",
    Combobox => "combobox",
    Container => "container",
    DataList => "data_list",
    DateField => "date_field",
    DatePicker => "date_picker",
    Dialog => "dialog",
    Divider => "divider",
    Drawer => "drawer",
    Fieldset => "fieldset",
    FileField => "file_field",
    Flex => "flex",
    Float => "float",
    FloatingWindow => "floating_window",
    FocusTrap => "focus_trap",
    Form => "form",
    FormGettingStarted => "form_getting_started",
    GettingStarted => "getting_started",
    Grid => "grid",
    Header => "header",
    HoverCard => "hover_card",
    Icon => "icon",
    Image => "image",
    ImageList => "image_list",
    Index => "index",
    Indicator => "indicator",
    Kbd => "kbd",
    Lightbox => "lightbox",
    List => "list",
    Loader => "loader",
    Mark => "mark",
    Marquee => "marquee",
    Menu => "menu",
    Menubar => "menubar",
    Modal => "modal",
    MultiSelect => "multi_select",
    NativeSelect => "native_select",
    NavLink => "nav_link",
    Notifications => "notifications",
    NumberField => "number_field",
    Overlay => "overlay",
    Pagination => "pagination",
    Paper => "paper",
    PasswordField => "password_field",
    Performance => "performance",
    PhoneField => "phone_field",
    PinField => "pin_field",
    Popover => "popover",
    ProgressBar => "progress_bar",
    QrCode => "qr_code",
    RadioGroup => "radio_group",
    RangeSlider => "range_slider",
    ScrollArea => "scroll_area",
    Scroller => "scroller",
    SegmentedControl => "segmented_control",
    Select => "select",
    Sidebar => "sidebar",
    Skeleton => "skeleton",
    Slider => "slider",
    Splitter => "splitter",
    Spotlight => "spotlight",
    Stepper => "stepper",
    Styling => "styling",
    Switch => "switch",
    Table => "table",
    Tabs => "tabs",
    TagsField => "tags_field",
    Text => "text",
    TextField => "text_field",
    Textarea => "textarea",
    Theming => "theming",
    Timeline => "timeline",
    Title => "title",
    Tooltip => "tooltip",
    Tree => "tree",
    VisuallyHidden => "visually_hidden",
}
