[package]
name = "docs"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { version = "0.7.10", default-features = true, features = ["router"] }
libero = { path = "../libero", default-features = false, features = [
    "code-lang-rust",
    "code-lang-bash",
    "code-lang-markdown",
    "code-lang-html",
    "code-lang-css",
] }
