use crate::components::{DocPage, DocSection};
use dioxus::prelude::*;
use libero::{
    components::{Anchor, Box, Code, CodeBlock, Flex, Text},
    sx::sx,
    theme::Size,
    use_theme,
};

// snippet: item #[derive(Clone, PartialEq, Routable)] enum Route { #[route("/")] Home {} }
// snippet: item #[component] fn Home() -> Element { rsx! {} }
const CUSTOM_THEME: &str = r#"static THEME: Theme = Theme {
    primary: HexColor::new(0x7C3AED),
    spacing: Sizes::new(4, 8, 12, 16, 20, 24),
    ..Theme::DEFAULT
};

fn App() -> Element {
    rsx! {
        LiberoProvider {
            themes: &THEME,
            Router::<Route> {}
        }
    }
}"#;

const COMPONENT_DEFAULTS: &str = r#"static THEME: Theme = Theme {
    // Every component's own defaults are a struct of their own.
    mark: MarkDefaults { color: Color::Info },
    button: ButtonDefaults {
        radius: Size::Xl,
        ..ButtonDefaults::DEFAULT
    },
    ..Theme::DEFAULT
};"#;

// snippet: ignore - the themes and `Route` are the app's own
const THEME_SET: &str = r#"LiberoProvider {
    themes: ThemeSet::new().light(&LIGHT).dark(&DARK).named("sepia", &SEPIA),
    Router::<Route> {}
}"#;

// snippet: ignore - the icons are the docs site's own
const SCHEME_TOGGLE: &str = r#"let scheme = use_color_scheme();

rsx! {
    ActionIcon {
        aria_label: match scheme.resolved() {
            ColorScheme::Dark => "Switch to the light theme",
            ColorScheme::Light => "Switch to the dark theme",
        },
        onclick: move |_| scheme.toggle(),
        if scheme.resolved() == ColorScheme::Dark { SunIcon {} } else { MoonIcon {} }
    }
}"#;

// snippet: ignore - `Control` is the docs site's own
const READING_THE_THEME: &str = r#"let theme = use_theme();

Control::color("color").default(theme.mark.color.as_str())"#;

// snippet: ignore - CSS
const EMITTED_CSS: &str = r#":root {
  --lsx-primary-6: #7c3aed;
  --lsx-primary-contrast-6: #ffffff;
  --lsx-spacing-md: 12px;
  --lsx-radius-md: 8px;
}"#;

/// The palette rows: every color with a full 1-9 shade ramp.
const PALETTE: [&str; 8] = [
    "primary",
    "secondary",
    "success",
    "error",
    "warning",
    "info",
    "neutral",
    "muted",
];

#[component]
pub fn ThemingPage() -> Element {
    let theme = use_theme();
    let spacing_min = theme.spacing.get(Size::Xs);
    let spacing_max = theme.spacing.get(Size::Xxl);

    rsx! {
        DocPage {
            title: "Theming",
            markdown: "/md/theming.md",
            lead: rsx! {
                Text {
                    Code { source: "LiberoProvider" }
                    "'s "
                    Code { source: "themes" }
                    " takes a "
                    Code { source: "&'static Theme" }
                    " and defaults to "
                    Code { source: "Theme::DEFAULT" }
                    ". A theme is one plain struct with a color per role, the spacing and "
                    "radius scales, and a defaults struct per component. Customizing it is "
                    "struct update syntax over the default, in a "
                    Code { source: "static" }
                    "."
                }
                Text {
                    "The provider renders it once as custom properties on "
                    Code { source: ":root" }
                    ", so the strings in "
                    Code { source: "sx" }
                    " need no lookup in Rust. "
                    Code { source: "\"primary.3\"" }
                    " compiles to "
                    Code { source: "var(--lsx-primary-3)" }
                    "."
                }
            },
            DocSection {
                title: "A custom theme",
                Text {
                    "Only the fields you name change. The rest come from "
                    Code { source: "Theme::DEFAULT" }
                    ", a "
                    Code { source: "const" }
                    ", so it can seed a "
                    Code { source: "static" }
                    ". The provider takes a "
                    Code { source: "'static" }
                    " reference, so the theme is never cloned per component."
                }
                CodeBlock { source: CUSTOM_THEME, language: "rust" }
            }

            DocSection {
                title: "Colors",
                Text {
                    "Each palette role is a single "
                    Code { source: "HexColor" }
                    ". Its nine shades are generated by mixing towards white and black, so a "
                    "new brand color is one hex value, not a ramp you design. A bare name is "
                    "shade 6, the hex itself. Every shade has a "
                    Code { source: "-contrast" }
                    " twin, black or white, whichever reads on it, so a component can pick "
                    "legible text for any background. "
                    Code { source: "neutral" }
                    " is the dark text role a control uses when it should not compete with "
                    "the page's accent. "
                    Code { source: "muted" }
                    " is measured as distance from the page (borders, dividers, quiet text), "
                    "so it is greyish on a light theme and the reverse on a dark one."
                }
                Text {
                    "A color resolves through the role it is used in, so it stays legible "
                    "without every call site checking. "
                    Code { source: "color()" }
                    " asks for the text role and "
                    Code { source: "background()" }
                    " for the fill role, each its own ramp. The text ramp starts at the "
                    "palette color moved just far enough from the page to reach 4.5:1. The "
                    "fill ramp starts where its black or white foreground reaches it. So "
                    Code { source: "primary" }
                    " is "
                    Code { source: "#228BE6" }
                    " as a border, a ring or a decoration, and "
                    Code { source: "#1D78C8" }
                    " as a label or under white text. The muted ramp is taken literally, so "
                    "quiet text asks for it by name, with "
                    Code { source: "text-dimmed" }
                    ". The palette of the theme this site is running:"
                }
                Flex {
                    direction: "column",
                    gap: "xs",
                    for color in PALETTE {
                        Flex {
                            key: "{color}",
                            direction: "row",
                            gap: "xs",
                            Text {
                                size: "sm",
                                sx: sx().width("88px").flex_shrink("0").font_weight("600"),
                                "{color}"
                            }
                            for shade in 1..=9 {
                                Box {
                                    key: "{shade}",
                                    sx: sx()
                                        .flex("1")
                                        .padding("6px 0")
                                        .border_radius("xs")
                                        .text_align("center")
                                        .font_size("11px")
                                        .background(format!("{color}.{shade}"))
                                        .color(format!("{color}-contrast.{shade}")),
                                    "{shade}"
                                }
                            }
                        }
                    }
                }
            }

            DocSection {
                title: "Scales",
                Text {
                    Code { source: "spacing" }
                    " and "
                    Code { source: "radius" }
                    " are a "
                    Code { source: "Sizes<u8>" }
                    ", one pixel value per step from "
                    Code { source: "xs" }
                    " to "
                    Code { source: "xxl" }
                    ". Size words in "
                    Code { source: "sx" }
                    " resolve through them, and every component's "
                    Code { source: "size" }
                    ", "
                    Code { source: "gap" }
                    " and "
                    Code { source: "radius" }
                    " prop steps along them. This theme's spacing scale runs from "
                    Code { source: "{spacing_min}px" }
                    " to "
                    Code { source: "{spacing_max}px" }
                    ". Components with a size of their own ("
                    Code { source: "Dialog" }
                    ", "
                    Code { source: "Drawer" }
                    ", "
                    Code { source: "Sidebar" }
                    ") carry their own "
                    Code { source: "Sizes" }
                    " in their defaults struct."
                }
                Text {
                    Code { source: "elevation" }
                    " has the same shape in "
                    Code { source: "&'static str" }
                    ": one "
                    Code { source: "box-shadow" }
                    " per step, from "
                    Code { source: "xs" }
                    " for a resting surface to "
                    Code { source: "xxl" }
                    " for a modal. A "
                    Code { source: "Dialog" }
                    "'s shadow and an "
                    Code { source: "elevated" }
                    " button's come from it."
                }
            }

            DocSection {
                title: "Component defaults",
                Text {
                    "Every component's unset props come from its own struct on the theme, so "
                    "\"our buttons are always pill-shaped\" is a theme change, not a prop "
                    "repeated at every call site. Nested struct update works the same way, "
                    "seeded from the component's own "
                    Code { source: "DEFAULT" }
                    "."
                }
                CodeBlock { source: COMPONENT_DEFAULTS, language: "rust" }
            }

            DocSection {
                title: "Light and dark",
                Text {
                    "One theme is shorthand for a "
                    Code { source: "ThemeSet" }
                    " of only that theme. A set names every theme an app ships, and which is "
                    "its light and which its dark. An app that names none gets "
                    Code { source: "ThemeSet::DEFAULT" }
                    ", which pairs "
                    Code { source: "Theme::DEFAULT" }
                    " with "
                    Code { source: "Theme::DARK" }
                    ", so "
                    Code { source: "prefers-color-scheme" }
                    " works with no JavaScript. Both halves of the pair are in the sheet "
                    "from the first paint, so switching between them is one attribute on "
                    "the document root, without a re-render. The sun in the header switches "
                    "this site."
                }
                CodeBlock { source: THEME_SET, language: "rust" }
                Text {
                    Code { source: "ThemeSet::CATALOGUE" }
                    " holds every set the library ships: "
                    Code { source: "Libero" }
                    ", plus Ayu, Ayu Mirage, Catppuccin, Dracula, Ef Night, Everforest, "
                    "Flexoki, GitHub, Gruvbox, Gruvbox Classic, Gruvbox Soft, Kanagawa, "
                    "Kanagawa Dragon, kettek16, Nord, One, Osmium, Rosé Pine and Vague. "
                    "Each is a light and dark pair. Where a palette is dark-only upstream, "
                    "its light half is the palette's own light variant. Only Vague, Osmium "
                    "and kettek16 have none and get one derived from their dark half. The "
                    "chevron beside the scheme button in this site's header is built from "
                    "it, through "
                    Code { source: "use_theme_set()" }
                    ". A ported palette is ten hex values, and every ramp, role and contrast "
                    "twin derives from them. "
                    Code { source: "warning" }
                    " is the one role a ported theme does not take from its palette. Every "
                    "one keeps Libero's amber."
                }
                Text {
                    Code { source: "ColorSchemeButton" }
                    " is the ready-made switch, the one in this header. It steps from "
                    "following the platform, to the other scheme, to the platform's own "
                    "scheme pinned, and back, so a reader can always return to the "
                    "platform's choice. With "
                    Code { source: "themes" }
                    " it adds a theme-set picker beside it. Anything else is built on "
                    Code { source: "use_color_scheme()" }
                    ". "
                    Code { source: "setting()" }
                    " is what the app asked for and "
                    Code { source: "resolved()" }
                    " is the scheme on screen. "
                    Code { source: "set(ColorSchemeSetting::System)" }
                    " hands the choice back to the platform. On the web the choice is kept "
                    "in "
                    Code { source: "localStorage" }
                    ". An app that wants no flash on load pastes "
                    Code { source: "COLOR_SCHEME_RESTORE_SCRIPT" }
                    " into its own "
                    Code { source: "index.html" }
                    ", because the wasm bundle has not run when the first frame is painted."
                }
                CodeBlock { source: SCHEME_TOGGLE, language: "rust" }
                Text {
                    "A dark theme is a theme whose "
                    Code { source: "surface" }
                    " is dark. The palette bases can stay, because every role is derived "
                    "against the surface and every ramp is mixed between "
                    Code { source: "ink" }
                    " and "
                    Code { source: "surface" }
                    ". Only what is written as a literal CSS color has to change, which is "
                    "why "
                    Code { source: "Theme::DARK" }
                    " restates five "
                    Code { source: "*Defaults" }
                    "."
                }
            }

            DocSection {
                title: "Localization",
                Text {
                    "The words components say and how dates are written are not in the "
                    "theme. See "
                    Anchor { to: crate::Route::LocalizationPage {}, "Localization" }
                    "."
                }
            }

            DocSection {
                title: "Reading the theme",
                Text {
                    Code { source: "use_theme()" }
                    " returns the active "
                    Code { source: "&'static Theme" }
                    ". Components use it for values they cannot express as CSS, such as "
                    Code { source: "z_index" }
                    " or a default that changes which element renders. This docs site uses "
                    "it so a demo control opens on the theme's real default."
                }
                CodeBlock { source: READING_THE_THEME, language: "rust" }
            }

            DocSection {
                title: "What it emits",
                Text {
                    "One stylesheet, once, at the provider: a custom property per theme "
                    "value, plus a small reset. Nothing else in Libero reads the theme at "
                    "render time to produce CSS, so a component's styles can be one cached "
                    "class whatever the theme says."
                }
                CodeBlock { source: EMITTED_CSS, language: "css" }
            }
        }
    }
}
