use crate::components::{DocPage, DocSection};
use dioxus::prelude::*;
use libero::{
    components::{Box, Code, CodeBlock, Flex, Text},
    sx::sx,
    theme::Size,
    use_theme,
};

// snippet: item #[derive(Clone, PartialEq, Routable)] enum Route { #[route("/")] Home {} }
// snippet: item #[component] fn Home() -> Element { rsx! {} }
const CUSTOM_THEME: &str = r#"static THEME: Theme = Theme {
    primary: HexColor::new(0x7C3AED),
    spacing: Sizes::new(4, 8, 12, 16, 20, 24),
    ..Theme::DEFAULT
};

fn App() -> Element {
    rsx! {
        LiberoProvider {
            theme: &THEME,
            Router::<Route> {}
        }
    }
}"#;

const COMPONENT_DEFAULTS: &str = r#"static THEME: Theme = Theme {
    // Every component's own defaults are a struct of their own.
    mark: MarkDefaults { color: Color::Info },
    button: ButtonDefaults {
        radius: Size::Xl,
        ..ButtonDefaults::DEFAULT
    },
    ..Theme::DEFAULT
};"#;

// snippet: ignore - the themes and `Route` are the app's own
const THEME_SET: &str = r#"LiberoProvider {
    themes: ThemeSet::new().light(&LIGHT).dark(&DARK).named("sepia", &SEPIA),
    Router::<Route> {}
}"#;

// snippet: ignore - the icons are the docs site's own
const SCHEME_TOGGLE: &str = r#"let scheme = use_color_scheme();

rsx! {
    ActionIcon {
        aria_label: match scheme.resolved() {
            ColorScheme::Dark => "Switch to the light theme",
            ColorScheme::Light => "Switch to the dark theme",
        },
        onclick: move |_| scheme.toggle(),
        if scheme.resolved() == ColorScheme::Dark { SunIcon {} } else { MoonIcon {} }
    }
}"#;

// snippet: ignore - `Control` is the docs site's own
const READING_THE_THEME: &str = r#"let theme = use_theme();

Control::color("color").default(theme.mark.color.as_str())"#;

// snippet: ignore - CSS
const EMITTED_CSS: &str = r#":root {
  --lsx-primary-6: #7c3aed;
  --lsx-primary-contrast-6: #ffffff;
  --lsx-spacing-md: 12px;
  --lsx-radius-md: 8px;
}"#;

/// The palette rows: every color with a full 1-9 shade ramp.
const PALETTE: [&str; 8] = [
    "primary",
    "secondary",
    "success",
    "error",
    "warning",
    "info",
    "neutral",
    "muted",
];

#[component]
pub fn ThemingPage() -> Element {
    let theme = use_theme();
    let spacing_min = theme.spacing.get(Size::Xs);
    let spacing_max = theme.spacing.get(Size::Xxl);

    rsx! {
        DocPage {
            title: "Theming",
            markdown: "/md/theming.md",
            lead: rsx! {
                Text {
                    Code { source: "LiberoProvider" }
                    " takes a "
                    Code { source: "&'static Theme" }
                    " and defaults to "
                    Code { source: "Theme::DEFAULT" }
                    ". A theme is one plain struct - a color per role, the spacing and radius "
                    "scales, and a defaults struct per component - so customizing it is "
                    "struct update syntax over the default, in a "
                    Code { source: "static" }
                    "."
                }
                Text {
                    "The provider renders it once as custom properties on "
                    Code { source: ":root" }
                    ". That is why the strings in "
                    Code { source: "sx" }
                    " resolve: "
                    Code { source: "\"primary.3\"" }
                    " is not looked up in Rust, it compiles to "
                    Code { source: "var(--lsx-primary-3)" }
                    "."
                }
            },
            DocSection {
                title: "A custom theme",
                Text {
                    "Only the fields you name change; the rest come from "
                    Code { source: "Theme::DEFAULT" }
                    ", which is a "
                    Code { source: "const" }
                    " so it can seed a "
                    Code { source: "static" }
                    " one. The provider wants a reference with a "
                    Code { source: "'static" }
                    " lifetime, so the theme is never cloned per component - reading it is a "
                    "pointer copy."
                }
                CodeBlock { source: CUSTOM_THEME, language: "rust" }
            }

            DocSection {
                title: "Colors",
                Text {
                    "Each palette role is a single "
                    Code { source: "HexColor" }
                    ", and the nine shades below it are generated by mixing towards white "
                    "and black - so a new brand color is one hex value, not a ramp you have "
                    "to design. A bare name is shade 6, the hex itself. Every shade also has "
                    "a "
                    Code { source: "-contrast" }
                    " twin - black or white, whichever reads on it - which is what lets a "
                    "component pick legible text for a background it was handed. "
                    Code { source: "neutral" }
                    " is the text-dark role a control reaches for when it should not compete "
                    "with the page's accent; "
                    Code { source: "muted" }
                    " is the ramp measured as distance from the page - borders, dividers "
                    "and quiet text - so it is greyish on a light theme and the other way "
                    "round on a dark one. This is the palette of the "
                    "theme this site is running:"
                }
                Text {
                    "A colour is then resolved through the role it is used in, so it stays "
                    "legible without every call site checking. "
                    Code { source: "color()" }
                    " asks for the text role and "
                    Code { source: "background()" }
                    " for the fill role, and each is its own ramp: the text ramp starts at "
                    "the palette colour moved just far enough away from the page to clear "
                    "4.5:1 on it, the fill ramp at the colour moved just far enough for its "
                    "black-or-white foreground to clear it. So "
                    Code { source: "primary" }
                    " is still "
                    Code { source: "#228BE6" }
                    " as a border, a ring or a decoration, and resolves to "
                    Code { source: "#1D78C8" }
                    " as a label or under white text. The muted ramp is taken literally - it "
                    "is picked for how quiet it should look - so text that means to be quiet "
                    "asks for it by name, with "
                    Code { source: "text-dimmed" }
                    "."
                }
                Flex {
                    direction: "column",
                    gap: "xs",
                    for color in PALETTE {
                        Flex {
                            key: "{color}",
                            direction: "row",
                            gap: "xs",
                            Text {
                                size: "sm",
                                sx: sx().width("88px").flex_shrink("0").font_weight("600"),
                                "{color}"
                            }
                            for shade in 1..=9 {
                                Box {
                                    key: "{shade}",
                                    sx: sx()
                                        .flex("1")
                                        .padding("6px 0")
                                        .border_radius("xs")
                                        .text_align("center")
                                        .font_size("11px")
                                        .background(format!("{color}.{shade}"))
                                        .color(format!("{color}-contrast.{shade}")),
                                    "{shade}"
                                }
                            }
                        }
                    }
                }
            }

            DocSection {
                title: "Scales",
                Text {
                    Code { source: "spacing" }
                    " and "
                    Code { source: "radius" }
                    " are a "
                    Code { source: "Sizes<u8>" }
                    " - one pixel value per step from "
                    Code { source: "xs" }
                    " to "
                    Code { source: "xxl" }
                    ". They are what a size word in "
                    Code { source: "sx" }
                    " resolves through, and what every component's "
                    Code { source: "size" }
                    "/"
                    Code { source: "gap" }
                    "/"
                    Code { source: "radius" }
                    " prop steps along. This theme's spacing scale is "
                    Code { source: "{spacing_min}px - {spacing_max}px" }
                    ". Components with a size of their own - "
                    Code { source: "Dialog" }
                    ", "
                    Code { source: "Drawer" }
                    ", "
                    Code { source: "Sidebar" }
                    " - carry their own "
                    Code { source: "Sizes" }
                    " in their defaults struct rather than borrowing the spacing scale."
                }
                Text {
                    Code { source: "elevation" }
                    " is the same shape in "
                    Code { source: "&'static str" }
                    ": one "
                    Code { source: "box-shadow" }
                    " per step, "
                    Code { source: "xs" }
                    " resting to "
                    Code { source: "xxl" }
                    " for a modal. It is where a "
                    Code { source: "Dialog" }
                    "'s shadow and an "
                    Code { source: "elevated" }
                    " button's come from."
                }
            }

            DocSection {
                title: "Component defaults",
                Text {
                    "Every component's unset props come from its own struct on the theme, so "
                    "\"our buttons are always pill-shaped\" is a theme change, not a prop "
                    "repeated at every call site. Nested struct update works the same way, "
                    "seeded from the component's own "
                    Code { source: "DEFAULT" }
                    "."
                }
                CodeBlock { source: COMPONENT_DEFAULTS, language: "rust" }
            }

            DocSection {
                title: "Light and dark",
                Text {
                    Code { source: "LiberoProvider" }
                    " takes a "
                    Code { source: "ThemeSet" }
                    " rather than one theme: it names every theme an app ships and "
                    "designates which is its light and which its dark. An app that names "
                    "none at all gets "
                    Code { source: "ThemeSet::DEFAULT" }
                    ", which pairs "
                    Code { source: "Theme::DEFAULT" }
                    " with "
                    Code { source: "Theme::DARK" }
                    ", so "
                    Code { source: "prefers-color-scheme" }
                    " already works with no JavaScript. The pair is emitted into the sheet "
                    "up front, so switching between the two is one attribute on the "
                    "document root - no re-render to see the new colours, right on the "
                    "first paint. The sun above switches this site."
                }
                CodeBlock { source: THEME_SET, language: "rust" }
                Text {
                    Code { source: "ThemeSet::CATALOGUE" }
                    " holds every set the library ships: our own "
                    Code { source: "Libero" }
                    ", plus Ayu, Ayu Mirage, Catppuccin, Dracula, Ef Night, Everforest, "
                    "Flexoki, GitHub, Gruvbox, Gruvbox Classic, Gruvbox Soft, Kanagawa, "
                    "Kanagawa Dragon, kettek16, Nord, One, Osmium, Rosé Pine and Vague. "
                    "Each is a light/dark pair: where a palette is dark-only upstream, "
                    "its light half is the palette's own light equivalent, and only "
                    "Vague, Osmium and kettek16, which have none, get one derived from "
                    "their dark half. The chevron beside the scheme button in "
                    "this site's header is built from it, through "
                    Code { source: "use_theme_set()" }
                    " - try it on any page. A ported palette is ten hex values and nothing "
                    "else: every ramp, role and contrast twin derives from them. "
                    Code { source: "warning" }
                    " is the one role a ported theme does not take from its palette: every "
                    "one keeps Libero's amber."
                }
                Text {
                    Code { source: "ColorSchemeButton" }
                    " is the ready-made switch - the one in this header. It steps through "
                    "following the platform, the other scheme, and the platform's own scheme "
                    "pinned, and back, so a reader can always return to the platform's choice "
                    "and to any devtools emulation of it; with "
                    Code { source: "themes" }
                    " it adds a theme-set picker beside it. Anything else is built on "
                    Code { source: "use_color_scheme()" }
                    ": "
                    Code { source: "setting()" }
                    " is what the app asked for and "
                    Code { source: "resolved()" }
                    " which scheme is on screen; "
                    Code { source: "set(ColorSchemeSetting::System)" }
                    " hands the choice back to the platform. On the web the choice is kept "
                    "in "
                    Code { source: "localStorage" }
                    ", and an app that wants no flash on load pastes "
                    Code { source: "COLOR_SCHEME_RESTORE_SCRIPT" }
                    " into its own "
                    Code { source: "index.html" }
                    " - the wasm bundle has not run when the first frame is painted."
                }
                CodeBlock { source: SCHEME_TOGGLE, language: "rust" }
                Text {
                    "A dark theme is a theme whose "
                    Code { source: "surface" }
                    " is dark: the palette bases do not have to move, because every role is "
                    "derived against the surface and every ramp is mixed between "
                    Code { source: "ink" }
                    " and "
                    Code { source: "surface" }
                    ". What has to be written down is anything spelled as a literal CSS "
                    "colour - "
                    Code { source: "Theme::DARK" }
                    " restates five "
                    Code { source: "*Defaults" }
                    " for exactly that."
                }
            }

            DocSection {
                title: "Reading the theme",
                Text {
                    Code { source: "use_theme()" }
                    " returns the active "
                    Code { source: "&'static Theme" }
                    ". Components use it for the values they cannot express as CSS ("
                    Code { source: "z_index" }
                    ", a default that changes which element renders); this docs site uses it "
                    "so a demo control can open on the theme's real default instead of a "
                    "hardcoded one."
                }
                CodeBlock { source: READING_THE_THEME, language: "rust" }
            }

            DocSection {
                title: "What it emits",
                Text {
                    "One stylesheet, once, at the provider - a custom property per theme "
                    "value, plus a small reset. Nothing else in Libero reads the theme at "
                    "render time to produce CSS, which is why a component's styles can be "
                    "one cached class no matter what the theme says."
                }
                CodeBlock { source: EMITTED_CSS, language: "css" }
            }
        }
    }
}
