use crate::components::{DocPage, DocSection};
use dioxus::prelude::*;
use libero::{
    components::{Box, Code, CodeBlock, Flex, Text},
    sx::sx,
    theme::Size,
    use_theme,
};

// snippet: item #[derive(Clone, PartialEq, Routable)] enum Route { #[route("/")] Home {} }
// snippet: item #[component] fn Home() -> Element { rsx! {} }
const CUSTOM_THEME: &str = r#"static THEME: Theme = Theme {
    primary: HexColor::new(0x7C3AED),
    spacing: Sizes::new(4, 8, 12, 16, 20, 24),
    ..Theme::DEFAULT
};

fn App() -> Element {
    rsx! {
        LiberoProvider {
            theme: &THEME,
            Router::<Route> {}
        }
    }
}"#;

const COMPONENT_DEFAULTS: &str = r#"static THEME: Theme = Theme {
    // Every component's own defaults are a struct of their own.
    mark: MarkDefaults { color: Color::Info },
    button: ButtonDefaults {
        radius: Size::Xl,
        ..ButtonDefaults::DEFAULT
    },
    ..Theme::DEFAULT
};"#;

// snippet: ignore - `Control` is the docs site's own
const READING_THE_THEME: &str = r#"let theme = use_theme();

Control::color("color").default(theme.mark.color.as_str())"#;

// snippet: ignore - CSS
const EMITTED_CSS: &str = r#":root {
  --lsx-primary-6: #7c3aed;
  --lsx-primary-contrast-6: #ffffff;
  --lsx-spacing-md: 12px;
  --lsx-radius-md: 8px;
}"#;

/// The palette rows: every color with a full 1-9 shade ramp.
const PALETTE: [&str; 8] = [
    "primary",
    "secondary",
    "success",
    "error",
    "warning",
    "info",
    "neutral",
    "grey",
];

#[component]
pub fn ThemingPage() -> Element {
    let theme = use_theme();
    let spacing_min = theme.spacing.get(Size::Xs);
    let spacing_max = theme.spacing.get(Size::Xxl);

    rsx! {
        DocPage {
            title: "Theming",
            markdown: "/md/theming.md",
            lead: rsx! {
                Text {
                    Code { source: "LiberoProvider" }
                    " takes a "
                    Code { source: "&'static Theme" }
                    " and defaults to "
                    Code { source: "Theme::DEFAULT" }
                    ". A theme is one plain struct - a color per role, the spacing and radius "
                    "scales, and a defaults struct per component - so customizing it is "
                    "struct update syntax over the default, in a "
                    Code { source: "static" }
                    "."
                }
                Text {
                    "The provider renders it once as custom properties on "
                    Code { source: ":root" }
                    ". That is why the strings in "
                    Code { source: "sx" }
                    " resolve: "
                    Code { source: "\"primary.3\"" }
                    " is not looked up in Rust, it compiles to "
                    Code { source: "var(--lsx-primary-3)" }
                    "."
                }
            },
            DocSection {
                title: "A custom theme",
                Text {
                    "Only the fields you name change; the rest come from "
                    Code { source: "Theme::DEFAULT" }
                    ", which is a "
                    Code { source: "const" }
                    " so it can seed a "
                    Code { source: "static" }
                    " one. The provider wants a reference with a "
                    Code { source: "'static" }
                    " lifetime, so the theme is never cloned per component - reading it is a "
                    "pointer copy."
                }
                CodeBlock { source: CUSTOM_THEME, language: "rust" }
            }

            DocSection {
                title: "Colors",
                Text {
                    "Each palette role is a single "
                    Code { source: "HexColor" }
                    ", and the nine shades below it are generated by mixing towards white "
                    "and black - so a new brand color is one hex value, not a ramp you have "
                    "to design. A bare name is shade 6, the hex itself. Every shade also has "
                    "a "
                    Code { source: "-contrast" }
                    " twin - black or white, whichever reads on it - which is what lets a "
                    "component pick legible text for a background it was handed. "
                    Code { source: "neutral" }
                    " is the text-dark role a control reaches for when it should not compete "
                    "with the page's accent; "
                    Code { source: "grey" }
                    " stays the mid-grey of borders and dividers. This is the palette of the "
                    "theme this site is running:"
                }
                Flex {
                    direction: "column",
                    gap: "xs",
                    for color in PALETTE {
                        Flex {
                            key: "{color}",
                            direction: "row",
                            gap: "xs",
                            Text {
                                size: "sm",
                                sx: sx().width("88px").flex_shrink("0").font_weight("600"),
                                "{color}"
                            }
                            for shade in 1..=9 {
                                Box {
                                    key: "{shade}",
                                    sx: sx()
                                        .flex("1")
                                        .padding("6px 0")
                                        .border_radius("xs")
                                        .text_align("center")
                                        .font_size("11px")
                                        .background(format!("{color}.{shade}"))
                                        .color(format!("{color}-contrast.{shade}")),
                                    "{shade}"
                                }
                            }
                        }
                    }
                }
            }

            DocSection {
                title: "Scales",
                Text {
                    Code { source: "spacing" }
                    " and "
                    Code { source: "radius" }
                    " are a "
                    Code { source: "Sizes<u8>" }
                    " - one pixel value per step from "
                    Code { source: "xs" }
                    " to "
                    Code { source: "xxl" }
                    ". They are what a size word in "
                    Code { source: "sx" }
                    " resolves through, and what every component's "
                    Code { source: "size" }
                    "/"
                    Code { source: "gap" }
                    "/"
                    Code { source: "radius" }
                    " prop steps along. This theme's spacing scale is "
                    Code { source: "{spacing_min}px - {spacing_max}px" }
                    ". Components with a size of their own - "
                    Code { source: "Dialog" }
                    ", "
                    Code { source: "Drawer" }
                    ", "
                    Code { source: "Sidebar" }
                    " - carry their own "
                    Code { source: "Sizes" }
                    " in their defaults struct rather than borrowing the spacing scale."
                }
                Text {
                    Code { source: "elevation" }
                    " is the same shape in "
                    Code { source: "&'static str" }
                    ": one "
                    Code { source: "box-shadow" }
                    " per step, "
                    Code { source: "xs" }
                    " resting to "
                    Code { source: "xxl" }
                    " for a modal. It is where a "
                    Code { source: "Dialog" }
                    "'s shadow and an "
                    Code { source: "elevated" }
                    " button's come from."
                }
            }

            DocSection {
                title: "Component defaults",
                Text {
                    "Every component's unset props come from its own struct on the theme, so "
                    "\"our buttons are always pill-shaped\" is a theme change, not a prop "
                    "repeated at every call site. Nested struct update works the same way, "
                    "seeded from the component's own "
                    Code { source: "DEFAULT" }
                    "."
                }
                CodeBlock { source: COMPONENT_DEFAULTS, language: "rust" }
            }

            DocSection {
                title: "Reading the theme",
                Text {
                    Code { source: "use_theme()" }
                    " returns the active "
                    Code { source: "&'static Theme" }
                    ". Components use it for the values they cannot express as CSS ("
                    Code { source: "z_index" }
                    ", a default that changes which element renders); this docs site uses it "
                    "so a demo control can open on the theme's real default instead of a "
                    "hardcoded one."
                }
                CodeBlock { source: READING_THE_THEME, language: "rust" }
            }

            DocSection {
                title: "What it emits",
                Text {
                    "One stylesheet, once, at the provider - a custom property per theme "
                    "value, plus a small reset. Nothing else in Libero reads the theme at "
                    "render time to produce CSS, which is why a component's styles can be "
                    "one cached class no matter what the theme says."
                }
                CodeBlock { source: EMITTED_CSS, language: "css" }
            }
        }
    }
}
